@url = http://localhost:8080

POST {{url}}/api/admin/getUser HTTP/1.1
Content-Type: application/json
Cookie: session=e3VzZXJuYW1lOiBhZG1pbn0=.0.WRCGhR0Vg4at1rRr1SwU0u9dxd4

{
  "_username": "user",
}

###
