@url = http://localhost:8080

POST {{url}}/api/activate HTTP/1.1
Content-Type: application/json

{
  "username": "user",
  "hash": "NzRhZTRlZDA2ZWFjZjNjOTJjNjA1NGJiMjg5YTgzMjk1YzRkODZmYmNkMWIyZWIwNTI3NmM4ZmMyZWJkMjM1ZDoxNjU5Mjk5MTc5",
}
